# Generated by Django 4.1.5 on 2023-01-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ProductsName', models.CharField(max_length=100)),
                ('CategoriesName', models.CharField(max_length=100)),
            ],
        ),
    ]
