# Generated by Django 4.1.5 on 2023-01-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('UsuarioId', models.AutoField(primary_key=True, serialize=False)),
                ('UsuariosNombre', models.CharField(max_length=100)),
            ],
        ),
    ]
